In [2]:
import pandas as pd
import numpy as np

In [3]:
miles = pd.DataFrame({'farthest_run_mi': [50,62, np.nan, 100, 26,13 ,31, 56]})

In [4]:
miles

farthest_run_mi
0             50.0
1             62.0
2              NaN
3            100.0
4             26.0
5             13.0
6             31.0
7             56.0

In [5]:
miles.isna().sum()

farthest_run_mi    1
dtype: int64

In [6]:
from sklearn.impute import SimpleImputer

In [7]:
imp_mean = SimpleImputer(strategy = 'mean')

In [8]:
imp_mean.fit_transform(miles)

array([[ 50.        ],
       [ 62.        ],
       [ 48.28571429],
       [100.        ],
       [ 26.        ],
       [ 13.        ],
       [ 31.        ],
       [ 56.        ]])

In [13]:
imp_median = SimpleImputer(strategy = 'median')

In [15]:
imp_median.fit_transform(miles)

array([[ 50.],
       [ 62.],
       [ 50.],
       [100.],
       [ 26.],
       [ 13.],
       [ 31.],
       [ 56.]])

In [45]:
imp_mode = SimpleImputer(strategy = 'most_frequent') #for mode

In [17]:
imp_mode.fit_transform(miles)

array([[ 50.],
       [ 62.],
       [ 13.],
       [100.],
       [ 26.],
       [ 13.],
       [ 31.],
       [ 56.]])

In [18]:
imp_const = SimpleImputer(strategy = 'constant', fill_value = 13)

In [19]:
imp_const.fit_transform(miles)

array([[ 50.],
       [ 62.],
       [ 13.],
       [100.],
       [ 26.],
       [ 13.],
       [ 31.],
       [ 56.]])

In [20]:
names = pd.DataFrame({
    'names': ['ronaldo', 'messi', 'trent', np.nan, 'pedri', 'maradona']
})

In [21]:
names

names
0   ronaldo
1     messi
2     trent
3       NaN
4     pedri
5  maradona

In [24]:
imp_constant_cat = SimpleImputer(strategy = 'constant', fill_value = 'kroos')

In [25]:
imp_constant_cat.fit_transform(names)

array([['ronaldo'],
       ['messi'],
       ['trent'],
       ['kroos'],
       ['pedri'],
       ['maradona']], dtype=object)

To show which data is specifically filled i.e previously null add_indicator is used.

In [26]:
imp_mean_marked = SimpleImputer(strategy ='mean', add_indicator = True)

In [27]:
imp_mean_marked.fit_transform(miles)

array([[ 50.        ,   0.        ],
       [ 62.        ,   0.        ],
       [ 48.28571429,   1.        ],
       [100.        ,   0.        ],
       [ 26.        ,   0.        ],
       [ 13.        ,   0.        ],
       [ 31.        ,   0.        ],
       [ 56.        ,   0.        ]])

In [38]:
df = pd.DataFrame(
    { 'Name' : ['Pessi', 'ronaldo', 'Neymar', 'Mbappe', np.nan, 'Rudiger', 'Rodri'],
      'Goals_scored_24': [6, 10, np.nan, 12, 9, 3, 13 ]  
})

In [39]:
df

Name  Goals_scored_24
0    Pessi              6.0
1  ronaldo             10.0
2   Neymar              NaN
3   Mbappe             12.0
4      NaN              9.0
5  Rudiger              3.0
6    Rodri             13.0

In [40]:
from sklearn.compose import make_column_transformer

In [41]:
ct = make_column_transformer(
    (imp_constant_cat, ['Name']),
    (imp_mean, ['Goals_scored_24']),
     remainder = 'drop'


)

In [46]:
ct.set_output(transform = 'pandas')

ColumnTransformer(transformers=[('simpleimputer-1',
                                 SimpleImputer(fill_value='kroos',
                                               strategy='constant'),
                                 ['Name']),
                                ('simpleimputer-2', SimpleImputer(),
                                 ['Goals_scored_24'])])

In [43]:
df_pandas = ct.fit_transform(df)

In [44]:
df_pandas

simpleimputer-1__Name  simpleimputer-2__Goals_scored_24
0                 Pessi                          6.000000
1               ronaldo                         10.000000
2                Neymar                          8.833333
3                Mbappe                         12.000000
4                 kroos                          9.000000
5               Rudiger                          3.000000
6                 Rodri                         13.000000